[package]
name = "hochzeitsfest"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
toml = { version = "0.8.20", default-features = false, features = ["parse"] }
